### ISSUE TITLE
[VS] Multiple matches not working

### ISSUE THREAD

**Issue by jerone** [editorconfig/editorconfig#176] opened 2014-10-06 19:11 UTC
According to the documentation one can use the following to match multiple different files:
```ini
# Matches the exact files either package.json or .travis.yml
[{package.json,.travis.yml}]
indent_style = space
```
Another comment in the documentation says that this feature is available since EditorConfig Core 0.11.0.

After seeing commit https://github.com/editorconfig/editorconfig-visualstudio/commit/f206140ea3d527c55be97f7848f394452ec8862a it says the implemented Core version is 0.11.5, but in the Visual Studio version it doesn't seems to work.

Is this a bug or a missing feature?

**Comment by Vertigo093i** [comment] 2015-03-25 17:08
@xuhdev , `[*.{json,yml}]` doesn't work either for me.

**Comment by jedmao** [comment] 2015-03-25 17:56
@Vertigo093i what version of the VS plugin are you using and what happens if you run the shell command for the file in question (e.g., `editorconfig package.json`)?

**Comment by Vertigo093i** [comment] 2015-03-26 07:27
@jedmao, latest available. To be precise, 0.5.0.
Running `editorconfig` 0.12.1 definitely shows correct settings.
But running `editorconfig` 0.11.5.20130520 (which as I understand is used by the VS package) shows output from the `[*]` section does not take into account the desired section.

**Comment by xuhdev** [comment] 2015-03-26 08:13
@Vertigo093i I'm not sure, does the visual studio version come from [here](https://chocolatey.org/packages/editorconfig.core)?

**Comment by jedmao** [comment] 2015-03-26 08:35
It does look like the last core update was 0.11.5, as @Vertigo093i says. See https://github.com/editorconfig/editorconfig-visualstudio/commit/f206140ea3d527c55be97f7848f394452ec8862a

**Comment by Vertigo093i** [comment] 2015-03-26 10:02
@xuhdev, this is the command-line tool you mentioned. The Visual Studio extension comes from [here](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328).

**Comment by xuhdev** [comment] 2015-03-26 18:34
I used this file:

```ini
root = true

[*]
indent_size = 2

[*.{json,yml}]
indent_size = 4
```

`editorconfig /path/to/a.json` gives me the correct `indent_size = 4`. The version is 0.11.5. @jedmao Are you able to reproduce it?

**Comment by jedmao** [comment] 2015-03-26 19:29
Yes. I think I've had this problem for a while now in VS. I've just dodged it by avoiding the syntax. We definitely need to publish a new VS plugin with the new 0.12 core.

**Comment by twojtowi** [comment] 2015-10-06 18:57
Since one year had just passed since opening of this issue it is fair to ask whether community is still interested in fixing it? For me it is a serious blocker which forces to use a really long configuration files if you want to support multiple file extensions (you have to define it one by one vs. wildcards).

**Comment by am11** [comment] 2015-10-20 08:58
Hey guys, I was hitting the same issue with overridden rules. I haven't figured out whether the issue exists in [core](https://github.com/editorconfig/editorconfig-core-c/tree/c5e2a58085d6d3aee926668d069899e4153a0887), [wrapper](https://github.com/editorconfig/editorconfig-visualstudio/tree/c0ea678/Wrapper) or the [managed](https://github.com/editorconfig/editorconfig-visualstudio/tree/c0ea678/Plugin) layer, but to workaround the misbehaviour, I used CRLF linefeeds in `.editorconfig` file itself and it worked. Meaning, open `.editorconfig` in notepad and make sure to have `\r\n` line breaks.

I agree with @jedmao that the plugin needs to be updated with latest core (preferably -- but not necessarily -- using P/Invoke and purging out the wrapper project for simplicity + transparency).

I will try to find time to work on it (not sooner than two weeks), unless someone else wants to take a stab at it.. :)

**Comment by am11** [comment] 2015-10-20 09:53
There is more to it.

This rule:

```ini
[*.{js,json,yml}]
indent_size=2
```

works. But the following variants do `not` work:

1. 

```ini
[*.{js, json, yml}] # space after comma, it will only apply rule to *.js
indent_size=2
```

2.

```ini
[{*.js,*.json,*.yml}] # this syntax is not supported
indent_size=2
```

**Comment by Mpdreamz** [comment] 2016-06-20 10:30
The `master` branch in core now works against the managed version (c# core implementation) of editorconfig 0.12.0. This should be fixed.

**Closed by Mpdreamz** 2016-06-20 10:30 UTC
Labels: plugin - visual studio
