### ISSUE TITLE
VisualStudio plugin doesn't apply editorconfig settings

### ISSUE THREAD

**Issue by LegalizeAdulthood** [editorconfig/editorconfig#191] opened 2015-01-01 20:06 UTC
If I just open a file in a directory that has a .editorconfig in parent directories, then the settings are not applied.

I am just editing files in a folder for a project checked out from github that has no Visual Studio solution or project structure.

**Comment by jedmao** [comment] 2015-01-04 07:00
What version of the plugin are you using and how are you verifying that the settings are not applied?

**Comment by LegalizeAdulthood** [comment] 2015-01-05 07:01
I'm running version 0.5.0.

When I open the file, none of the settings are applied: line endings aren't unified, trailing whitespace remains, tabs remain, etc.

**Comment by jedmao** [comment] 2015-01-05 07:05
I think I understand. Are you expecting the plugin to autofix your file on open? If so, this is not the purpose of the plugin. It's only intended to set your configuration settings; hence, the name EditorConfig.

Can you verify that new indentations are according to your .editorconfig file's settings and that line endings are fixed and trailing whitespace removed on file save?

**Comment by LegalizeAdulthood** [comment] 2015-01-05 07:10
I'm pretty sure it wasn't changing the settings for new edits as well, i.e. it was still using tabs to insert.  Have you tried reproducing it?

**Comment by LegalizeAdulthood** [comment] 2015-01-05 07:10
I'm using VS 2013 Update 4

**Comment by jedmao** [comment] 2015-01-05 17:05
I use the plugin every day. I'm also using VS 2013 Update 4 w/ EditorConfig 0.5.0 and I'm unable to reproduce.

To properly test, I'll need the following:
1. Example folder structure.
2. Placement of your .editorconfig file(s) in that structure.
3. Contents of each .editorconfig file.
4. Example source file that is not picking up expected changes.

**Comment by jedmao** [comment] 2015-01-16 06:21
@LegalizeAdulthood any updates on this?

**Comment by LegalizeAdulthood** [comment] 2015-01-16 19:48
Haven't had a chance to go back and try and reproduce it yet.  I just started a new job :smile_cat: .

**Comment by jedmao** [comment] 2015-01-17 02:08
OK. Closing until further details can be provided.

**Closed by jedmao** 2015-01-17 02:08 UTC

**Comment by AuthorProxy** [comment] 2015-05-27 12:46
The most actual problem now is that VS EditorConfig don't change encoding for file, as specified.
Sublime plugin works as expected at the same scenario.

userfolder --- global editor config
rootfoolder --- project editorconfig
rootfoolder/folder1//folder2/folder3/folder4/editedfile.cs

project editorconfig:
````
root = true

[*]
charset = utf-8
end_of_line = crlf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
indent_size = 4
indent_style = space
trim_trailing_whitespace = false

[*.cs]
indent_size = 4
indent_style = space




[*.json]
indent_size = 2
indent_style = space

[*.yml]
indent_size = 2
indent_style = space

[*.yaml]
indent_size = 2
indent_style = space

[*.js]
indent_size = 2
indent_style = space

[*.coffee]
indent_size = 2
indent_style = space

[*.css]
indent_size = 2
indent_style = space

[*.html]
indent_size = 2
indent_style = space

[*.cshtml]
charset = utf-8-bom
indent_size = 2
indent_style = space

[*.aspx]
charset = utf-8-bom
indent_size = 2
indent_style = space

[*.ascx]
charset = utf-8-bom
indent_size = 2
indent_style = space

[*.ashx]
charset = utf-8-bom
indent_size = 2
indent_style = space

[*.Master]
charset = utf-8-bom
indent_size = 2
indent_style = space




[*.kproj]
indent_size = 2
indent_style = space

[*.csproj]
indent_size = 2
indent_style = space

[*.ps1]
indent_size = 2
indent_style = space

[*.resx]
indent_size = 2
indent_style = space

[*.rst]
indent_size = 2
indent_style = space




[*.sln]
indent_size = 2
indent_style = tab

[*.proj]
indent_size = 2
indent_style = tab

[*.props]
indent_size = 2
indent_style = tab

[*.targets]
indent_size = 2
indent_style = tab




[*.min.*]
indent_style = ignore
trim_trailing_whitespace = false
insert_final_newline = ignore
````

I cannot combine this properties cause it doesn't work at Visual Studio too.
