### ISSUE TITLE
Visual Studio Plugin: Only works once

### ISSUE THREAD

**Issue by Francismori7** [editorconfig/editorconfig#181] opened 2014-10-31 17:03 UTC
Hi there,

Using VS2013 Ultimate here, using Web Essentials. I have my root .editorconfig file set up, and it looks like it only works once. By that I mean that if I change something in my editorconfig file, I have to close all my files and open them again for the Format Document command to pick up the new stuff. Shouldn't it work by default without needing to close the files?

**Comment by Mpdreamz** [comment] 2016-06-20 10:36
Hi Guys,

Closing this issue due to it being pretty old and was never able to be reproduced fully.

If you (anyone in the thread or future googler) still have this issue please reopen an issue here: https://github.com/editorconfig/editorconfig-visualstudio/issues.

The build in `master` should be a lot easier too now, all the sdk prerequisites are nuget packages and we moved from the original core implementation to a managed one.

**Closed by Mpdreamz** 2016-06-20 10:36 UTC
Labels: plugin - visual studio

**Comment by timabell** [comment] 2016-06-20 10:44
:+1:
