### ISSUE TITLE
Rules for naming editor/plugin-specific keys?

### ISSUE THREAD

**Issue by sdavids** [editorconfig/editorconfig#516] opened 2024-09-20 10:08 UTC
[Supported Pairs](https://spec.editorconfig.org/#supported-pairs)

> Here is the list of all keys defined by this version of this specification

[IntelliJ](https://www.jetbrains.com/help/idea/editorconfig.html#heqdcl_31)

> Generic IntelliJ options that have the `ij_` prefix and are applicable to all languages

[Visual Studio](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options#example-editorconfig-file)

> dotnet_separate_import_directive_groups = false
> csharp_preserve_single_line_blocks = true
---

Please clarify how editors/plugins can add to the [existing keys](https://spec.editorconfig.org/#supported-pairs).

One "MUST", "SHOULD", or "MAY" add a prefix/suffix? — [Key words for use in RFCs to Indicate Requirement Levels](https://www.rfc-editor.org/rfc/rfc2119)

---

How would you introduce a new core property key in the future without requiring editors/plugins to use prefixes/suffixes?—Existing editors/plugins might already use a specific key.

Let's say you want to introduce an `ignore` key with the meaning A but there already exists an editor using `ignore` with meaning B.

**Comment by cxw42** [comment] 2024-09-23 18:46
The only widely-used standard I know of is reverse-DNS, so that's what I'd suggest for custom keys.  (Cf. toolconfig discussion draft https://github.com/editorconfig/editorconfig/issues/482#issuecomment-1403023825).  E.g.,
```ini
[*]
com.jetbrains.ij.visual_guides = ...
com.jetbrains.ij.java.blank_lines_after_imports = ...
com.microsoft.net.sort_system_directives_first = ...
com.microsoft.file_header_template = ...
```

**Comment by sdavids** [comment] 2024-09-24 16:01
[#322](https://github.com/editorconfig/editorconfig/issues/332) seems in analysis paralysis: 7 years old and its last activity is almost 1 year ago.

**Comment by sdavids** [comment] 2024-09-24 16:12
Something like

> Additional properties should have a key with a prefix identifying your editor/plugin; for now, the format of the prefix is not specified.

could be added now.

It is better to have something now than nothing.

**Comment by xuhdev** [comment] 2024-09-24 22:18
Yes, I agree it's better to have something than nothing. Now I think the jetbrain idea is better: Whenever there's a dot in the key, it's something customized by the editor.

We considered extensibility of keys, and the whole structure is friendly to new keys without much intervention from the spec. But we made the mistake of not setting a standard for custom keys from individual editor plugins.

**Comment by cxw42** [comment] 2024-09-24 23:52
I had a chance to look through #332 myself, and I do think this is part of that discussion.  For example, @ppalaga's https://github.com/editorconfig/editorconfig/issues/332#issuecomment-391255016 :

> What we need is an offcial EditorConfig support for property namespaces. In other words, we need to introduce a way how can it be decided for a given property if it is either
> 
> (a) general - its semantics is defined by EditorConfig or
> 
> (b) domain specific - its semantics is defined by the owner of the domain namespace

And @florianb's https://github.com/editorconfig/editorconfig/issues/332#issuecomment-653068557 :

> Probably it would be a good idea to (at least) recommend using domain names as property-prefix?

I am closing this ticket as duplicate of #332 and will post over there to bump the discussion!

**Closed by cxw42** 2024-09-24 23:52 UTC
