### ISSUE TITLE
VS2010 cannot find EditorConfigWrapper.dll

### ISSUE THREAD

**Issue by mcsmit** [editorconfig/editorconfig#215] opened 2015-04-17 08:04 UTC
Today I started working with EditorConfig and it works fine on Notepad++. But after installing the VS extension it does not work and the VS ActivityLog.xml tells be about a File Not Found exception for EditorConfigWrapper.dll.
I tried to install it outside VS and using the extension manager, started VS as administrator, but still no luck.
I searched on my drives but could not find the file anywhere, so the 'File Not Found' exception is correct. Where should the file exists after installing? And how can I solve my problem?
I installed version 0.5.0 and my system is Windows 7 64 bit.

**Comment by Mpdreamz** [comment] 2016-06-20 10:48
Closing this because `master` of editorconfig-visualstudio now uses the managed port of the editorconfig core and no longer needs the `EditorConfigWrapper.dll`. 

Thanks for reporting this, sorry for never being able to reproduce or reporting back.

**Closed by Mpdreamz** 2016-06-20 10:48 UTC
Labels: bug, plugin - visual studio
