### ISSUE TITLE
VisualStudio: Reset settings when loading initially

### ISSUE THREAD

**Issue by cmerat** [editorconfig/editorconfig#198] opened 2015-01-30 23:00 UTC
Since the next project or solution that gets opened may not have any .editorconfig file present, the plugin should reset to whatever settings were present before they were overwritten by an .editorconfig file. This would make switching between projects that both use .editorconfig and not without the last loaded .editorconfig settings bleeding into any solutions loaded afterwards that don't have a file.

**Comment by jedmao** [comment] 2015-01-31 17:58
Are you currently experiencing this issue? Because the way the plugin works now is that it leaves your global settings in tact. As you switch between files, it loads the appropriate EditorConfig settings for each file. If you close a tab (file) or lose focus, it will reload your global settings. As such, switching between projects should be flawless.

**Comment by cmerat** [comment] 2015-02-02 13:37
Yes, at least for tabs. Repro steps:
1) Default settings is use 4 spaces instead of tabs
2) Open solution with an .editorconfig file that specifies indent_style=tabs
3) Modify any file (add a few tabs, make sure that it's really tabs that are added).
4) Do not close the file, simply close VS
5) Open another solution without an .editorconfig file
6) Tabs are added although I'd expect it to be spaces

**Comment by jedmao** [comment] 2015-02-12 05:17
Thanks @cmerat. With the steps you provided I am unable to reproduce. I followed your steps to the T and everything worked as it should. I actually expected it to fail and was hoping to fix your issue, but sadly I cannot reproduce it.

1. I set my default settings to 4 spaces indentation on all files.
2. I opened one of my solutions (they are always set to tabs). BTW, it should be `indent_style = tab` not `tabs`. Refer to [editorconfig.org](http://editorconfig.org/).
3. I edited a file and verified tabs were being inserted. I have whitespace visible, so I could see them as they were being entered.
4. I had 3 files up and closed VS w/o closing any files.
5. I opened a project that was not my own. They were using 2 spaces for indentation and had no editorconfig file.
6. When I hit tab, 4 spaces were inserted, to my surprise, but this is exactly how the plugin is supposed to work.

The only way I can imagine the settings getting borfed is if VS crashes at some point while your global settings have been modified. I have yet to see this happen, but truthfully, I rarely work in projects without an editorconfig file. If they don't have one, I tend to add one.

I'm somewhat relieved by the fact I can't reproduce your issue, but I'm also upset that it's causing you grief. I wish I could be of service, but we might have to wait until we have more information. If VS crashing is the issue, it's probably an edge case that can't really be solved.

Let me know if you get any more information. Sorry you have to go through this.

**Closed by jedmao** 2015-02-12 05:17 UTC

**Comment by jedmao** [comment] 2015-02-12 05:28
For the record, I'm using:
- Visual Studio Professional 2013 Update 4
- [EditorConfig 0.5.0](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328)
- [TabSanity 0.1.5](https://visualstudiogallery.msdn.microsoft.com/ac4d4d6b-b017-4a42-8f72-55f0ffe850d7) &ndash; works great alongside EditorConfig.

**Comment by cmerat** [comment] 2015-02-12 16:54
@jedmao I'm using Resharper, could this be interfering?

**Comment by jedmao** [comment] 2015-02-12 17:04
@cmerat I'm also using ReSharper and you know the best way to find that out is to disable ReSharper and see if it still presents a problem.
