### ISSUE TITLE
Automatic Linter Configuration?

### ISSUE THREAD

**Issue by andrewdeandrade** [editorconfig/editorconfig#183] opened 2014-11-14 06:43 UTC
Are there any plans for performing automatic linter configuration in future versions of .editorconfig.

It would be really nice to be able to define on a filetype-by-filetype basis what linters are enabled and disabled and the paths to the `.rc` and `.ignore` files for each linter. Automatic setup of syntastic, SublimeLinter and flycheck would be most awesome.
##

**Comment by matrixise** [comment] 2017-04-04 08:36
Hi,
any news about this issue ?

thank you

**Comment by xuhdev** [comment] 2017-04-04 08:46
@matrixise I don't have time to work on [this project](https://github.com/xuhdev/editorconfig-cf) alone, but I have already written a contribution guideline. Feel free to contribute to the part that is relevant to your own language (I'm not know-all-languages person...).

**Comment by cxw42** [comment] 2021-07-17 15:35
Can this be closed as a duplicate of #103?

**Comment by xuhdev** [comment] 2021-07-17 19:13
> Can this be closed as a duplicate of #103?

I believe so. Closing now.

**Closed by xuhdev** 2021-07-17 19:13 UTC
